vich_uploader:
    db_driver: orm

    mappings:
        category_images:
           uri_prefix: '%images_directory_category%'
           upload_destination: '%kernel.project_dir%/public/img/category'
           namer: Vich\UploaderBundle\Naming\UniqidNamer

        event_images:
           uri_prefix: '%images_directory_event%'
           upload_destination: '%kernel.project_dir%/public/img/event'
           namer: Vich\UploaderBundle\Naming\UniqidNamer

